In [4]:
import pandas as pd
import os

In [9]:
data_folder = os.path.join(os.path.dirname(os.getcwd()), 'PastSeasonsData')
print(data_folder)

/home/itan/Documents/Backend/PastSeasonsData

In [10]:
def get_file_path(filename):
    return os.path.join(base_folder, filename)

# File names
files_2024 = ['202324_cleaned_players.csv', '202324_fixtures.csv', '202324_teams.csv']
files_2023 = ['202223_cleaned_players.csv', '202223_fixtures.csv', '202223_teams.csv']

# Load 2024 data
players_2024 = pd.read_csv(get_file_path(files_2024[0]))
fixtures_2024 = pd.read_csv(get_file_path(files_2024[1]))
teams_2024 = pd.read_csv(get_file_path(files_2024[2]))

# Load 2023 data
players_2023 = pd.read_csv(get_file_path(files_2023[0]))
fixtures_2023 = pd.read_csv(get_file_path(files_2023[1]))
teams_2023 = pd.read_csv(get_file_path(files_2023[2]))

In [16]:
players_2023.first_name.sort_values().head(10)

143        Aaron
522        Aaron
713        Aaron
12         Aaron
288    Abdoulaye
78          Adam
163         Adam
400         Adam
638         Adam
157         Adam
Name: first_name, dtype: object

Index(['first_name', 'second_name', 'goals_scored', 'assists', 'total_points',
       'minutes', 'goals_conceded', 'creativity', 'influence', 'threat',
       'bonus', 'bps', 'ict_index', 'clean_sheets', 'red_cards',
       'yellow_cards', 'selected_by_percent', 'now_cost', 'element_type'],
      dtype='object')

In [20]:
mergedgw2023 = pd.read_csv('https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/refs/heads/master/data/2023-24/gws/merged_gw.csv')

In [21]:
mergedgw2023

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Femi Seriki,DEF,Sheffield Utd,0.5,0,0,0,0,0.0,653,...,0,0.0,0,0,0,0,40,True,0,1
1,Jack Hinshelwood,MID,Brighton,1.5,0,0,0,0,0.0,621,...,4,0.0,0,0,0,0,45,True,0,1
2,Jadon Sancho,MID,Man Utd,3.0,0,0,4,0,11.3,397,...,1,8.0,1,0,0,0,70,True,0,1
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0.1,0,0,0,0,0.0,487,...,0,0.0,0,0,0,0,40,True,0,1
4,Vitaly Janelt,MID,Brentford,2.1,0,0,6,0,11.5,105,...,2,17.0,2,0,0,0,55,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Kyle Walker,DEF,Man City,7.5,0,0,15,0,11.6,369,...,3,0.0,2,-3560,44071,47631,55,True,0,38
29721,Jacob Brown,FWD,Luton,0.0,0,0,0,0,0.0,631,...,2,0.0,0,86,216,130,49,True,0,38
29722,Vicente Guaita,GK,Crystal Palace,0.0,0,0,0,0,0.0,227,...,5,0.0,0,-120,0,120,44,True,0,38
29723,Braian Ojeda Rodríguez,MID,Nott'm Forest,0.0,0,0,0,0,0.0,459,...,1,0.0,0,-1,0,1,45,False,0,38
29724,Mads Bech Sørensen,DEF,Brentford,0.0,0,0,0,0,0.0,93,...,2,0.0,0,-65,0,65,40,True,0,38